language: ruby

matrix:
  include:
    - os: osx
      osx_image: xcode8.0
      rvm: system
    - os: linux
      rvm: 2.0.0

before_install:
  - export HOMEBREW_DEVELOPER="1"
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      HOMEBREW_REPOSITORY="$(brew --repo)";
      sudo chown -R "$USER" "$HOMEBREW_REPOSITORY";
      git -C "$HOMEBREW_REPOSITORY" reset --hard origin/master;
      brew update || brew update;
    else
      HOMEBREW_REPOSITORY="$HOME/Homebrew";
      git clone --depth=1 https://github.com/Homebrew/brew "$HOMEBREW_REPOSITORY";
      export PATH="$HOMEBREW_REPOSITORY/bin:$PATH";
      umask 022;
    fi
  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
  - mkdir -p "$(dirname "$HOMEBREW_TAP_DIR")"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"
  - ulimit -n 1024

script:
  - brew test-bot

notifications:
  email:
    on_success: never
    on_failure: always
