# don't try to be clever with the Gemfile
language: c

branches:
  only:
    - master

before_install:
  - HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew
  - sudo mkdir -p /home/linuxbrew
  - sudo git clone https://github.com/Homebrew/brew "$HOMEBREW_REPOSITORY"
  - sudo mkdir -p "$HOMEBREW_REPOSITORY/Library/Taps/homebrew"
  - sudo ln -s "$PWD" "$HOMEBREW_REPOSITORY/Library/Taps/homebrew/homebrew-test-bot"
  - sudo chown -R "$USER" "$HOMEBREW_REPOSITORY"
  - export PATH="$HOMEBREW_REPOSITORY/bin:/usr/bin:/bin"
  - umask 022
  - chmod 644 Formula/*.rb
  # trigger vendored ruby installation
  - brew help

script:
  - brew test-bot
