language: c
cache:
  directories:
    - $HOME/Library/Caches/Homebrew/style
    - $HOME/Library/Caches/Homebrew/tests
    - $HOME/Library/Homebrew/vendor/bundle
branches:
  only:
    - master
matrix:
  fast_finish: true
  include:
    - os: osx
      compiler: clang
      osx_image: xcode9.2
    - os: linux
      compiler: gcc
      sudo: false

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      MACOS="1";
      HOMEBREW_REPOSITORY="$(brew --repo)";
      sudo chown -R "$USER" "$HOMEBREW_REPOSITORY";
      HOMEBREW_CORE_TAP_DIR="$(brew --repo "homebrew/core")";
    else
      LINUX="1";
      HOMEBREW_REPOSITORY="$HOME/Homebrew";
      export PATH="$HOMEBREW_REPOSITORY/bin:$PATH";
    fi
  # umask 022 fixes Linux `brew tests` failures;
  - if [ "$LINUX" ]; then
      umask 022;
      chmod 644 Formula/*.rb;
    fi
  - if [ "$MACOS" ]; then
      travis_retry git -C "$HOMEBREW_REPOSITORY" fetch --depth=50 origin;
    else
      travis_retry git clone --depth=50 https://github.com/Homebrew/brew "$HOMEBREW_REPOSITORY";
    fi
  - if [ "$LINUX" ]; then
      HOMEBREW_CORE_TAP_DIR="$(brew --repo "homebrew/core")";
    fi
  - if [ "$MACOS" ]; then
      travis_retry git -C "$HOMEBREW_CORE_TAP_DIR" fetch --depth=1 origin;
    else
      travis_retry git clone --depth=1 https://github.com/Homebrew/homebrew-core "$HOMEBREW_CORE_TAP_DIR";
    fi
  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
  - mkdir -p "$HOMEBREW_TAP_DIR"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"
  # trigger vendored ruby installation
  - brew help

script:
  - brew test-bot
  - brew test-bot --ci-upload --dry-run
