jobs:
- job: macOS
  pool:
    vmImage: xcode9-macos10.13
  steps:
    - bash: |
        sudo xcode-select --switch /Applications/Xcode_10.app/Contents/Developer
        brew update-reset /usr/local/Homebrew
        ln -s "$PWD" "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-test-bot"
        brew test-bot --coverage
      displayName: Run brew test-bot
      env:
        HOMEBREW_GITHUB_API_TOKEN: $(github.publicApiToken)

    - task: PublishTestResults@2
      displayName: Publish test-bot test results
      condition: succeededOrFailed()
      inputs:
        testRunner: JUnit
        testResultsFiles: brew-test-bot.xml

    - task: PublishCodeCoverageResults@1
      displayName: Publish brew tests code coverage
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: $(Build.SourcesDirectory)/coverage/coverage.xml
        reportDirectory: $(Build.SourcesDirectory)/coverage
        failIfCoverageEmpty: false

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
    - bash: |
        git clone https://github.com/Homebrew/brew "$HOME/Homebrew"
        mkdir -p "$HOME/Homebrew/Library/Taps/linuxbrew"
        ln -s "$PWD" "$HOME/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot"
        "$HOME/Homebrew/bin/brew" test-bot
      displayName: brew test-bot
      env:
        HOMEBREW_GITHUB_API_TOKEN: $(github.publicApiToken)
        HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1

    - task: PublishTestResults@2
      displayName: Publish test-bot test results
      condition: succeededOrFailed()
      inputs:
        testRunner: JUnit
        testResultsFiles: brew-test-bot.xml
