jobs:
- job: macOS
  pool:
    vmImage: xcode9-macos10.13
  steps:
    - bash: |
        rm -rf /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask*
        brew update-reset
        ln -s "$PWD" "/usr/local/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot"
        brew test-bot --coverage
      displayName: Run brew test-bot
      env:
        HOMEBREW_GITHUB_API_TOKEN: $(github.publicApiToken)

    - task: PublishTestResults@2
      displayName: Publish test-bot test results
      inputs:
        testRunner: JUnit
        testResultsFiles: brew-test-bot.xml

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
    - bash: |
        git clone https://github.com/Homebrew/brew "$HOME/Homebrew"
        mkdir -p "$HOME/Homebrew/Library/Taps/linuxbrew"
        ln -s "$PWD" "$HOME/Homebrew/Library/Taps/linuxbrew/homebrew-test-bot"
        "$HOME/Homebrew/bin/brew" test-bot
      displayName: brew test-bot
      env:
        HOMEBREW_GITHUB_API_TOKEN: $(github.publicApiToken)
